from typing import Any, Dict

def generate_markdown_report(final_state: Dict[str, Any]) -> str:
    """
    Generates a structured Markdown report from the final AgentState.
    """
    question = final_state.get("question", "N/A")
    analysis = final_state.get("analysis_result", "No analysis generated.")
    goal = final_state.get("goal_consensus", {})
    plan = final_state.get("node_plan", [])
    v_res = final_state.get("verifier_result", {})
    loops = final_state.get("loop_count", 1)
    models = ", ".join(final_state.get("model_history", {"local"}))
    
    # Format Plan Table
    plan_md = "| Step | Role | Description | Keywords |\n|---|---|---|---|\n"
    for step in plan:
        kws = ", ".join(step.get("search_keywords", []))
        plan_md += f"| {step.get('step_name')} | {step.get('role')} | {step.get('description')} | {kws} |\n"

    # Format Sub-results
    sub_res_md = "\n\n".join(final_state.get("sub_results", []))
    
    # Build full report
    report = f"""# Legal Analysis Report

## 1. Request Details
**Query / File**: {question}
**Core Intent**: {goal.get('consensus_intent', 'N/A')}
**Priority**: {goal.get('priority', 'N/A')}
**Scope**: {goal.get('scope', 'N/A')}

## 2. Final Analysis
{analysis}

---
## 3. Execution Details

### 3.1 Workflow Plan
{plan_md}

### 3.2 Sub-Task Findings
<details>
<summary>Click to view detailed findings</summary>

{sub_res_md}

</details>

### 3.3 Quality Assurance
- **Verifier Score**: {v_res.get('score', 'N/A')}/10
- **Status**: {'Passed' if v_res.get('passed', True) else 'Forced Output'}
- **Iterations**: {loops}
- **Models Used**: {models}

*Generated by Legal AI Multi-Agent System*
"""
    return report
